# Apollo Space Mission Control - Dynamic Wallpaper Sync
preload = /home/diogo/Space-Race-Theme/wallpapers/historical/nasa_gene_kranz_console.jpg
wallpaper = , /home/diogo/Space-Race-Theme/wallpapers/historical/nasa_gene_kranz_console.jpg
splash = false
ipc = true
