[General]
background=background.jpg
type=image
color=#14171d
fontSize=11
fontFamily="JetBrainsMono Nerd Font"
accentColor=#ffb000
telemetryGreen=#2ef788
alertRed=#ff3333
textColor=#f4eedb
dimTextColor=#8c9ba5
