# 🚀 SPACE RACE MISSION CONTROL // KOSMOS-VFD MISSION PROFILE (SOVIET VFD)
set -g status-style "bg=#0c1b18,fg=#36b89c"
set -g status-left-style "bg=#48e9c2,fg=#060e0c,bold"
set -g status-right-style "bg=#0c1b18,fg=#226b5c"
set -g window-status-style "bg=#0c1b18,fg=#226b5c"
set -g window-status-current-style "bg=#122e28,fg=#48e9c2,bold"
set -g window-status-activity-style "bg=#0c1b18,fg=#48e9c2"
set -g pane-border-style "fg=#122e28"
set -g pane-active-border-style "fg=#48e9c2"
set -g message-style "bg=#48e9c2,fg=#060e0c,bold"
set -g message-command-style "bg=#122e28,fg=#48e9c2"
