# DEC VT100 / P1 Phosphor Green CRT Terminal Palette
foreground                      #33ff33
background                      #0a0e0a
selection_foreground            #0a0e0a
selection_background            #33ff33
cursor                          #33ff33
cursor_text_color               #0a0e0a

color0 #0a0e0a
color8 #1a331a
color1 #00cc00
color9 #33ff33
color2 #33ff33
color10 #66ff66
color3 #00aa00
color11 #55ff55
color4 #009900
color12 #44ff44
color5 #00bb00
color13 #77ff77
color6 #00ee00
color14 #88ff88
color7 #c8ffc8
color15 #ffffff

background_opacity 0.92
window_padding_width 10
